# --- vffac specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000

# episode runner
# runner: "episode"

# parallel runner
runner: "parallel"
batch_size_run: 8
t_max: 10050000

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
#l earner: "q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
comm_coef: 0.05
min_uncer: 0.1

n_value: 64
n_key: 64
n_query: 64
mac: "tmac_p2p_comm_mac"
agent: "tmac_p2p_comm_rnn_delay_msg"
lambda_entropy: 0.0
learner: "tmac_p2p_comm_learner"

td_lambda: 1
q_lambda: False

# none, constant, Ndistribution
msg_delay_type: "none"
delay_value: 1
delay_scale: 2

name: "tmac_p2p_comm"
