env: "sc2v2"

env_args:
  map_name: null
  time_limit: 150
  fully_observable: False
  replay_dir: null
  replay_prefix: null

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 50000
learner_log_interval: 50000
t_max: 10050000
save_model_interval: 1000000 # Save models after this many timesteps
